#!/usr/bin/env python3
"""
build_by_packmol.py — Assemble multi-component MD systems via Packmol.

ALL systems go through Packmol. No hand-written coordinates.
Molecules are sourced from ~/.motus/molecules/ (populated by fetch_molecule.py).

Supports:
  - Pure solvent (water box)
  - Solute + solvent mixtures
  - Solid-liquid interfaces
  - Multi-component custom systems

Usage:
    # Water box
    python3 build_by_packmol.py --components water:884 --box 3.0 --out /tmp/sys/

    # Methane + water
    python3 build_by_packmol.py --components methane:30,water:884 --box 3.0 --out /tmp/sys/

    # Solid-liquid interface
    python3 build_by_packmol.py --components ice:500,water:884 --box 3.5 --interface 0.5 --out /tmp/sys/

    # Full custom
    python3 build_by_packmol.py --components ethanol:100,water:500,urea:10 --box 3.5 --density 0.9 --out /tmp/sys/
"""
import sys
import os
import argparse
import subprocess
import math
from pathlib import Path
from datetime import datetime

CACHE_DIR = Path.home() / ".motus" / "molecules"
MOLECULE_MAP = {
    "water": "water.pdb",
    "h2o": "water.pdb",
    "methane": "methane.pdb",
    "ch4": "methane.pdb",
    "ethanol": "ethanol.pdb",
    "urea": "urea.pdb",
    "benzene": "benzene.pdb",
    "caffeine": "caffeine.pdb",
    # Add more as needed
}


def resolve_molecule(name: str) -> str | None:
    """Resolve molecule name to PDB file path."""
    name_lower = name.lower().strip()
    filename = MOLECULE_MAP.get(name_lower, f"{name_lower}.pdb")
    candidates = [
        CACHE_DIR / filename,
        Path(name) if os.path.isabs(name) else Path.cwd() / name,
    ]
    for c in candidates:
        if c.exists() and c.stat().st_size > 50:
            return str(c.resolve())
    return None


def count_atoms_in_pdb(pdb_path: str) -> int:
    """Count ATOM/HETATM records in PDB."""
    with open(pdb_path) as f:
        return sum(1 for l in f if l.startswith(("ATOM  ", "HETATM")))


def generate_packmol_input(components: dict, box_nm: float, out_dir: Path,
                           interface_z: float = None, tolerance: float = 2.0,
                           seed: int = -1) -> str:
    """
    Generate Packmol input file.
    
    components: {name: (pdb_path, count)}
    box_nm: box size in nm (cubic)
    """
    box_a = box_nm * 10.0  # nm → Å for Packmol
    
    lines = [
        f"# Packmol input generated by MOTUS",
        f"# {datetime.now().isoformat()}",
        f"tolerance {tolerance}",
        f"filetype pdb",
        f"output {out_dir}/packed.pdb",
        f"",
    ]
    
    for mol_name, (pdb_path, count) in components.items():
        if interface_z is not None and mol_name != list(components.keys())[0]:
            # Interface mode: first component = substrate, rest = liquid
            # Place liquid molecules above the interface
            z_min = interface_z * 10.0  # nm → Å
            constraint = f"inside box 0. 0. {z_min} {box_a} {box_a} {box_a}"
        else:
            constraint = f"inside box 0. 0. 0. {box_a} {box_a} {box_a}"
        
        lines.append(f"structure {pdb_path}")
        lines.append(f"  number {count}")
        lines.append(f"  {constraint}")
        lines.append(f"end structure")
        lines.append(f"")
    
    return "\n".join(lines)


def run_packmol(inp_path: str, out_dir: Path) -> bool:
    """Run Packmol, return success. Uses stdin=open(file) to avoid Fortran pipe seek error."""
    try:
        with open(inp_path) as f:
            r = subprocess.run(
                ["packmol"],
                stdin=f,
                capture_output=True, text=True,
                timeout=300, cwd=str(out_dir),
            )
        if r.returncode != 0:
            print(f"PACKMOL FAILED (exit={r.returncode})", file=sys.stderr)
            # Print last meaningful output
            for line in r.stdout.split('\n')[-10:]:
                if line.strip():
                    print(f"  {line.strip()}", file=sys.stderr)
            return False
        return (out_dir / "packed.pdb").exists()
    except subprocess.TimeoutExpired:
        print("PACKMOL TIMED OUT after 300s", file=sys.stderr)
        return False
    except FileNotFoundError:
        print("ERROR: packmol not installed. Run: sudo apt-get install packmol", file=sys.stderr)
        return False


def packed_to_gro(packed_pdb: Path, gro_path: Path, box_nm: float) -> bool:
    """Convert packed PDB to GRO format with proper box vectors."""
    box_str = f"{box_nm} {box_nm} {box_nm}"
    try:
        r = subprocess.run([
            "bash", "-c",
            f'source /home/xenon/tools/gromacs-2026/bin/GMXRC 2>/dev/null && '
            f'gmx editconf -f {packed_pdb} -o {gro_path} -box {box_str}',
        ], capture_output=True, text=True, timeout=30)
        return r.returncode == 0 and gro_path.exists()
    except Exception:
        return False


def write_topology(out_dir: Path, components: dict):
    """Write GROMACS topology file."""
    has_water = "water" in [n.lower() for n in components]
    special_mols = [n for n in components if n.lower() != "water"]
    
    lines = [
        '#include "oplsaa.ff/forcefield.itp"',
    ]
    if has_water:
        lines.append('#include "oplsaa.ff/spce.itp"')
    for mol in special_mols:
        mol_lower = mol.lower()
        if mol_lower == "methane":
            lines.append('#include "oplsaa.ff/methane.itp"')
        else:
            # Generic: assume user has the itp file
            lines.append(f'#include "{mol_lower}.itp"')
    
    lines.append("")
    lines.append("[ System ]")
    names = [f"{n}({c})" for n, (_, c) in components.items()]
    lines.append(" + ".join(names))
    lines.append("")
    lines.append("[ Molecules ]")
    for mol_name, (_, count) in components.items():
        mol_upper = mol_name.upper()[:3] if mol_name.lower() == "water" else mol_name.upper()[:4]
        if mol_name.lower() == "water":
            mol_upper = "SOL"
        elif mol_name.lower() == "methane":
            mol_upper = "CH4"
        lines.append(f"{mol_upper}    {count}")
    
    (out_dir / "topol.top").write_text("\n".join(lines) + "\n")


def build(args: dict) -> str:
    """
    Build a molecular system using Packmol.
    
    args:
        components: list of {name, count} dicts, e.g. [{"name":"water","count":884}, {"name":"methane","count":30}]
        box_size_nm: float, cubic box size in nm
        out_dir: str, output directory
        interface_z: float (optional), z-position of interface in nm (for solid-liquid)
        density: float (optional), target density in g/mL
        tolerance: float, Packmol tolerance (default 2.0)
    """
    comp_list = args.get("components", [])
    box_nm = args.get("box_size_nm", 3.0)
    out_dir = args.get("out_dir", "/tmp/motus_system")
    interface_z = args.get("interface_z")
    tolerance = args.get("tolerance", 2.0)
    
    out_path = Path(out_dir)
    out_path.mkdir(parents=True, exist_ok=True)
    
    # Resolve all molecules
    components = {}
    unresolved = []
    for c in comp_list:
        name = c["name"]
        count = c["count"]
        pdb = resolve_molecule(name)
        if pdb:
            # Quick sanity check
            n_atoms = count_atoms_in_pdb(pdb)
            components[name] = (pdb, count)
        else:
            unresolved.append(name)
    
    if unresolved:
        return (f"ERROR: Could not find PDB files for: {', '.join(unresolved)}\n"
                f"  Run: python3 scripts/fetch_molecule.py --name <molecule>\n"
                f"  Available in cache: {list(CACHE_DIR.glob('*.pdb'))}")
    
    if not components:
        return "ERROR: No components specified"
    
    # Generate Packmol input
    inp = generate_packmol_input(components, box_nm, out_path, interface_z, tolerance)
    inp_path = out_path / "packmol.inp"
    inp_path.write_text(inp)
    
    lines = [f"Building system in {box_nm:.1f} nm box:"]
    total_atoms = 0
    for name, (pdb, count) in components.items():
        n_atom = count_atoms_in_pdb(pdb)
        total = n_atom * count
        total_atoms += total
        lines.append(f"  {name}: {count} × {n_atom} atoms = {total} atoms")
    lines.append(f"  Total: {total_atoms} atoms")
    
    # Run Packmol
    ok = run_packmol(str(inp_path), out_path)
    if not ok:
        return "ERROR: Packmol failed. Check packmol.inp for details."
    
    # Convert to GRO
    packed = out_path / "packed.pdb"
    gro = out_path / "system.gro"
    if not packed_to_gro(packed, gro, box_nm):
        return "ERROR: Failed to convert PDB to GRO format"
    
    # Write topology
    write_topology(out_path, components)
    
    lines.append(f"\n✓ System built at {out_dir}/")
    lines.append(f"  system.gro + topol.top ready for MD")
    return "\n".join(lines)


# ===== CLI =====
def main():
    p = argparse.ArgumentParser(description="Build MD system with Packmol")
    p.add_argument("--components", required=True,
                   help="Comma-separated name:count, e.g. 'water:884,methane:30'")
    p.add_argument("--box", type=float, default=3.0, help="Box size in nm")
    p.add_argument("--out", required=True, help="Output directory")
    p.add_argument("--interface", type=float, help="Interface Z position in nm")
    p.add_argument("--density", type=float, help="Target density g/mL")
    p.add_argument("--tolerance", type=float, default=2.0, help="Packmol tolerance")
    args = p.parse_args()
    
    comp_list = []
    for part in args.components.split(","):
        name, count = part.strip().split(":")
        comp_list.append({"name": name.strip(), "count": int(count)})
    
    result = build({
        "components": comp_list,
        "box_size_nm": args.box,
        "out_dir": args.out,
        "interface_z": args.interface,
        "density": args.density,
        "tolerance": args.tolerance,
    })
    
    print(result)
    sys.exit(0 if "✓" in result else 1)


if __name__ == "__main__":
    main()
