#!/bin/bash
# ============================================================
# lammps-md.sh — Automated LAMMPS MD Pipeline  |  MOTUS v0.0.1
# ============================================================
# Usage:
#   lammps-md.sh <job_dir> [OPTIONS]
#
# The job directory must contain:
#   system.data (LAMMPS data file)
#
# Options:
#   -t, --time <ps>        Simulation time (default: 2000)
#   -i, --interval <ps>    Recording interval (default: 1)
#   -T, --temperature <K>  Temperature (default: 300)
#   -P, --pressure <bar>   Pressure (default: 1.01325)
#   --gpu                  Use GPU acceleration
#   --no-gpu               Force CPU
#   --clean                Remove backup files
#
# Workflow: Minimize → NVT → NPT → Production
# ============================================================

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

log()    { echo -e "${GREEN}[✓]${NC} $*"; }
warn()   { echo -e "${YELLOW}[!]${NC} $*"; }
error()  { echo -e "${RED}[✗]${NC} $*"; exit 1; }
header() { echo -e "\n${BOLD}${CYAN}━━━ $* ━━━${NC}"; }

usage() { head -24 "$0" | grep '^#' | sed 's/^# \?//'; exit 0; }

# ── Find LAMMPS ──
LMP="${LMP:-}"
find_lammps() {
    [[ -n "$LMP" ]] && command -v "$LMP" &>/dev/null && return 0
    for p in lmp /home/$USER/tools/lammps-*/install/bin/lmp /home/$USER/.local/bin/lmp; do
        if [[ -x "$p" ]]; then LMP="$p"; return 0; fi
    done
    return 1
}
find_lammps || error "LAMMPS not found. Set LMP=/path/to/lmp"

# ── Defaults ──
SIM_TIME=2000; REC_INTERVAL=1; TEMP=300; PRESSURE=1.01325
USE_GPU=1; DO_CLEAN=0
TIMESTEP=0.5  # fs (0.5 fs for all-atom with flexible bonds)

# ── Parse args ──
JOB_DIR=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help) usage ;;
        -t|--time)       SIM_TIME="$2"; shift 2 ;;
        -i|--interval)   REC_INTERVAL="$2"; shift 2 ;;
        -T|--temperature) TEMP="$2"; shift 2 ;;
        -P|--pressure)   PRESSURE="$2"; shift 2 ;;
        --gpu)           USE_GPU=1; shift ;;
        --no-gpu)        USE_GPU=0; shift ;;
        --clean)         DO_CLEAN=1; shift ;;
        --lmp)           LMP="$2"; shift 2 ;;
        *)               JOB_DIR="$1"; shift ;;
    esac
done

[[ -z "$JOB_DIR" ]] && error "No job directory provided."
[[ ! -d "$JOB_DIR" ]] && error "Directory not found: $JOB_DIR"
JOB_DIR=$(realpath "$JOB_DIR")
JOB_NAME=$(basename "$JOB_DIR")
cd "$JOB_DIR"

DATA=$(ls system.data 2>/dev/null | head -1)
[[ -z "$DATA" ]] && error "No system.data found in $JOB_DIR"

# ── GPU setup ──
GPU_FLAG=""
if [[ "$USE_GPU" -eq 1 ]] && nvidia-smi &>/dev/null 2>&1; then
    GPU_FLAG="-sf gpu -pk gpu 1"
    log "GPU acceleration enabled"
fi

# Derived values
NSTEPS=$(awk "BEGIN {printf \"%d\", ${SIM_TIME} * 1000 / ${TIMESTEP}}")
DUMP_FREQ=$(awk "BEGIN {printf \"%d\", ${REC_INTERVAL} * 1000 / ${TIMESTEP}}")
THERMO_FREQ=$DUMP_FREQ

header "LAMMPS MD Pipeline: $JOB_NAME"
echo -e "  ${BOLD}Data:${NC}      $DATA"
echo -e "  ${BOLD}Sim time:${NC}  ${SIM_TIME} ps (${NSTEPS} steps, ${TIMESTEP} fs timestep)"
echo -e "  ${BOLD}Interval:${NC}  ${REC_INTERVAL} ps"
echo -e "  ${BOLD}Temp:${NC}      ${TEMP} K"

# ── Generate LAMMPS input script ──
log "Generating LAMMPS input..."

cat > in.prod << LMPEOF
# LAMMPS production MD — auto-generated by lammps-md.sh
# System: ${JOB_NAME}

units           real
atom_style      full
bond_style      harmonic
angle_style     harmonic
dihedral_style  opls
pair_style      lj/cut/coul/long 10.0 10.0
kspace_style    pppm 1e-4
pair_modify     mix geometric

read_data       ${DATA}

# Pair coefficients — use values from data file Pair Coeffs section
# (if not in data file, uncomment and set below)
# pair_coeff      1 1 0.1553 3.166  # O-O
# pair_coeff      1 2 0.0    0.0    # O-H
# pair_coeff      2 2 0.0    0.0    # H-H

# Neighbor list
neighbor        2.0 bin
neigh_modify    every 1 delay 0 check yes

# Thermostat + barostat
velocity        all create ${TEMP}.0 12345
# fix npt includes both thermostat + barostat (no need for separate fix nvt)
fix             npt all npt temp ${TEMP}.0 ${TEMP}.0 100.0 iso ${PRESSURE} ${PRESSURE} 1000.0

# Output
thermo          ${THERMO_FREQ}
thermo_style    custom step temp press pe ke etotal vol density
dump            traj all custom ${DUMP_FREQ} prod.lammpstrj id type x y z
dump_modify     traj sort id

# Run
timestep        ${TIMESTEP}
run             ${NSTEPS}

write_data      final.data
LMPEOF

# ── Run ──
header "Launching LAMMPS MD"
START_TIME=$(date +%s)

$LMP -in in.prod $GPU_FLAG 2>&1 | tee prod.log | grep -E "Step|Temp|Press|Loop|Perf|ERROR" | tail -20

EXIT_CODE=${PIPESTATUS[0]}
END_TIME=$(date +%s)
ELAPSED=$((END_TIME - START_TIME))

# ── Summary ──
echo ""
header "MD Complete"
echo -e "  ${BOLD}Wall time:${NC}  ${ELAPSED}s"
echo -e "  ${BOLD}Exit code:${NC}  $EXIT_CODE"

if [[ -f prod.log ]]; then
    STEPS_DONE=$(grep "Loop time" prod.log | awk '{print $7}' | head -1)
    PERF=$(grep "Loop time" prod.log | awk '{printf "%.1f", $3/3600*24*'${SIM_TIME}'/'${NSTEPS}'}' | head -1)
    echo -e "  ${BOLD}Steps:${NC}      ${STEPS_DONE:-N/A}"
fi

ls -lh prod.lammpstrj final.data 2>/dev/null | awk '{printf "  %-8s %s\n", $5, $NF}'

[[ "$DO_CLEAN" -eq 1 ]] && rm -f log.lammps

exit $EXIT_CODE
