#!/bin/bash
# ============================================================
# desmond-md.sh — Automated Schrödinger Desmond MD Pipeline
# ============================================================
# See SKILL.md for full usage instructions.
#
# Minimal usage:
#   ./desmond-md.sh <desmond_setup_XXXXX>
#   ./desmond-md.sh <desmond_setup_XXXXX> -t 2000 -i 1
#
# The setup folder must contain <name>-out.cms (from System Builder).
# Automatically creates desmond_md_job_XXXXX alongside it and runs the MD.
# ============================================================

set -euo pipefail

# ── Colors ──
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

# ── Defaults ──
SIM_TIME=2000          # ps
REC_INTERVAL=1         # ps
TEMPERATURE=300        # K
PRESSURE=1.01325       # bar
CUTOFF=5.0             # Å
CPU=1
GPU_LICENSE=16
SCHRODINGER="${SCHRODINGER:-/home/xenon/tools/schrodinger2025-2}"
OUTPUT_DIR=""

usage() {
    head -28 "$0" | grep '^#' | sed 's/^# \?//'
    exit 0
}

log()    { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()   { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()  { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }
header() { echo -e "\n${BOLD}${CYAN}━━━ $* ━━━${NC}"; }

# ── Parse args ──
SETUP_FOLDER=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        -t|--time)       SIM_TIME="$2"; shift 2 ;;
        -i|--interval)   REC_INTERVAL="$2"; shift 2 ;;
        -T|--temperature) TEMPERATURE="$2"; shift 2 ;;
        -P|--pressure)   PRESSURE="$2"; shift 2 ;;
        -c|--cutoff)     CUTOFF="$2"; shift 2 ;;
        --cpu)           CPU="$2"; shift 2 ;;
        --gpu-license)   GPU_LICENSE="$2"; shift 2 ;;
        --schrodinger)   SCHRODINGER="$2"; shift 2 ;;
        --output-dir)    OUTPUT_DIR="$2"; shift 2 ;;
        -h|--help)       usage ;;
        -*)              error "Unknown option: $1" ;;
        *)               SETUP_FOLDER="$1"; shift ;;
    esac
done

# ── Validation ──
[[ -z "$SETUP_FOLDER" ]] && error "No setup folder provided.\nUsage: $0 <desmond_setup_XXXXX> [OPTIONS]"
[[ ! -d "$SETUP_FOLDER" ]] && error "Setup folder not found: $SETUP_FOLDER"

SETUP_DIR=$(realpath "$SETUP_FOLDER")
SETUP_NAME=$(basename "$SETUP_DIR")

# Extract system name from "desmond_setup_XXXXX"
if [[ "$SETUP_NAME" =~ ^desmond_setup_(.+)$ ]]; then
    SYSTEM="${BASH_REMATCH[1]}"
else
    error "Setup folder must be named 'desmond_setup_XXXXX'\nGot: $SETUP_NAME"
fi

JOB_NAME="desmond_md_job_${SYSTEM}"

# Find output CMS from setup
CMS_INPUT=$(ls "$SETUP_DIR/${SETUP_NAME}-out.cms" 2>/dev/null || echo "")
[[ -z "$CMS_INPUT" ]] && error "No output CMS found in setup folder.\nExpected: $SETUP_DIR/${SETUP_NAME}-out.cms"

# Determine output directory
if [[ -z "$OUTPUT_DIR" ]]; then
    OUTPUT_DIR="$(dirname "$SETUP_DIR")/${JOB_NAME}"
fi
mkdir -p "$OUTPUT_DIR"

# Validate SCHRODINGER
[[ ! -d "$SCHRODINGER" ]] && error "SCHRODINGER not found: $SCHRODINGER\nSet with --schrodinger or export SCHRODINGER"
MULTISIM="$SCHRODINGER/utilities/multisim"
[[ ! -x "$MULTISIM" ]] && error "multisim not found: $MULTISIM"

# ── Calculate derived values ──
TOTAL_FRAMES=$(( SIM_TIME / REC_INTERVAL ))
TOTAL_PS=$SIM_TIME
CHKPT_INTERVAL=$(( TOTAL_PS / 10 ))
[[ $CHKPT_INTERVAL -lt 50 ]] && CHKPT_INTERVAL=50
MAEFF_INTERVAL=$CHKPT_INTERVAL

header "Desmond MD Pipeline"
echo -e "  ${BOLD}System:${NC}        $SYSTEM"
echo -e "  ${BOLD}Setup folder:${NC}  $SETUP_DIR"
echo -e "  ${BOLD}Output folder:${NC} $OUTPUT_DIR"
echo -e "  ${BOLD}Sim time:${NC}      ${TOTAL_PS} ps (${TOTAL_FRAMES} frames)"
echo -e "  ${BOLD}Record interval:${NC} ${REC_INTERVAL} ps"
echo -e "  ${BOLD}Temperature:${NC}   ${TEMPERATURE} K"
echo -e "  ${BOLD}Schrodinger:${NC}   $SCHRODINGER"

# ── Copy CMS input ──
log "Copying system from setup..."
cp "$CMS_INPUT" "$OUTPUT_DIR/${JOB_NAME}-in.cms"
cp "$CMS_INPUT" "$OUTPUT_DIR/${JOB_NAME}.cms"

# ── Generate .msj (equilibration protocol) ──
log "Generating $JOB_NAME.msj..."
cat > "$OUTPUT_DIR/${JOB_NAME}.msj" << MSJEOF
# Desmond standard NPT relaxation protocol
# Auto-generated by desmond-md.sh
# All times in ps, energy in kcal/mol
task {
  task = "desmond:auto"
  set_family = {
    desmond = {
      checkpt.write_last_step = no
    }
  }
}

simulate {
  title       = "Brownian Dynamics NVT, T = 10 K, small timesteps, and restraints on solute heavy atoms, 100ps"
  annealing   = off
  time        = 100
  timestep    = [0.001 0.001 0.003 ]
  temperature = 10.0
  ensemble = {
    class  = "NVT"
    method = "Brownie"
    brownie = {
      delta_max = 0.1
    }
  }
  polarization_restraints = full
  restraints.new = [
    {
      name            = posre_harm
      atoms           = solute_heavy_atom
      force_constants = 50.0
    }
  ]
  eneseq.interval = 0.3
}

simulate {
  title                   = "NVT, T = 10 K, small timesteps, and restraints on solute heavy atoms, 12ps"
  annealing               = off
  time                    = 12
  timestep                = [0.001 0.001 0.003]
  temperature             = 10.0
  polarization_restraints = full
  restraints.new = [
    {
      name            = posre_harm
      atoms           = solute_heavy_atom
      force_constants = 50.0
    }
  ]
  ensemble = {
    class          = NVT
    method         = Langevin
    thermostat.tau = 0.1
  }
  randomize_velocity.interval = 1.0
  eneseq.interval             = 0.3
  trajectory.center           = []
}

simulate {
  title                   = "NPT, T = 10 K, and restraints on solute heavy atoms, 12ps"
  annealing               = off
  time                    = 12
  temperature             = 10.0
  polarization_restraints = full
  restraints.existing     = retain
  ensemble = {
    class          = NPT
    method         = Langevin
    thermostat.tau = 0.1
    barostat  .tau = 50.0
  }
  randomize_velocity.interval = 1.0
  eneseq.interval             = 0.3
  trajectory.center           = []
}

simulate {
  title                   = "NPT and restraints on solute heavy atoms, 12ps"
  effect_if               = [["@*.*.annealing"] 'annealing = off temperature = "@*.*.temperature[0][0]"']
  time                    = 12
  polarization_restraints = full
  restraints.existing     = retain
  ensemble = {
    class          = NPT
    method         = Langevin
    thermostat.tau = 0.1
    barostat  .tau = 50.0
  }
  randomize_velocity.interval = 1.0
  eneseq.interval             = 0.3
  trajectory.center           = []
}

simulate {
  title     = "NPT and no restraints, 24ps"
  effect_if = [["@*.*.annealing"] 'annealing = off temperature = "@*.*.temperature[0][0]"']
  time      = 24
  ensemble = {
    class          = NPT
    method         = Langevin
    thermostat.tau = 0.1
    barostat  .tau = 2.0
  }
  polarization_restraints = decay
  eneseq.interval         = 0.3
  trajectory.center       = solute
}

simulate {
   cfg_file = "${JOB_NAME}.cfg"
   jobname  = "\$MAINJOBNAME"
   dir      = "."
   compress = ""
}
MSJEOF

# ── Generate .cfg (production run) ──
log "Generating $JOB_NAME.cfg..."
cat > "$OUTPUT_DIR/${JOB_NAME}.cfg" << CFGEOF
annealing = false
backend = {
}
bigger_rclone = false
box = ?
bulk_properties = false
checkpt = {
   first = 0.0
   interval = ${CHKPT_INTERVAL}.0
   name = "\$JOBNAME.cpt"
   write_last_step = true
}
cpu = ${CPU}
cutoff_radius = ${CUTOFF}
dipole_moment = false
ebias_force = false
elapsed_time = 0.0
energy_group = false
eneseq = {
   first = 0.0
   interval = ${REC_INTERVAL}.0
   name = "\$JOBNAME\$[_replica\$REPLICA\$].ene"
}
ensemble = {
   barostat = {
      tau = 2.0
   }
   class = NPT
   method = MTK
   thermostat = {
      tau = 1.0
   }
}
gaussian_force = false
glue = solute
lambda_dynamics = false
maeff_output = {
   center_atoms = solute
   first = 0.0
   interval = ${MAEFF_INTERVAL}.0
   name = "\$JOBNAME\$[_replica\$REPLICA\$]-out.cms"
   periodicfix = true
   trjdir = "\$JOBNAME\$[_replica\$REPLICA\$]_trj"
}
meta = false
meta_file = ?
msd = false
polarization_restraints = none
pressure = [${PRESSURE} isotropic ]
pressure_tensor = false
randomize_velocity = {
   first = 0.0
   interval = inf
   seed = 2007
   temperature = "@*.temperature"
}
restrain = none
restraints = {
   existing = ignore
   new = []
}
rnemd = false
simbox = {
   first = 0.0
   interval = 1.2
   name = "\$JOBNAME\$[_replica\$REPLICA\$]_simbox.dat"
}
spatial_temperature = false
surface_tension = 0.0
taper = false
temperature = [
   [${TEMPERATURE}.0 0 ]
]
time = ${TOTAL_PS}.0
timestep = [0.002 0.002 0.006 ]
trajectory = {
   center = []
   first = 0.0
   format = dtr
   frames_per_file = ${TOTAL_FRAMES}
   interval = ${REC_INTERVAL}.0
   name = "\$JOBNAME\$[_replica\$REPLICA\$]_trj"
   periodicfix = true
   write_last_step = true
   write_last_vel = false
   write_velocity = false
}
wall_force = false
CFGEOF

# ── Create tmp project dir ──
PROJ_DIR="$OUTPUT_DIR/.proj_tmp"
mkdir -p "$PROJ_DIR"

# ── Run ──
header "Launching Desmond MD"
log "Job name: $JOB_NAME"
log "Output dir: $OUTPUT_DIR"

cd "$OUTPUT_DIR"

START_TIME=$(date +%s)

# Capture multisim output to extract JobId
MULTISIM_OUT=$("$MULTISIM" \
    -JOBNAME "$JOB_NAME" \
    -HOST localhost \
    -maxjob 1 \
    -cpu "$CPU" \
    -m "${JOB_NAME}.msj" \
    -c "${JOB_NAME}.cfg" \
    -description "Molecular Dynamics - ${TOTAL_PS}ps" \
    "${JOB_NAME}.cms" \
    -mode umbrella \
    -PROJ "$PROJ_DIR" \
    -DISP append \
    -o "${JOB_NAME}-out.cms" \
    -lic "DESMOND_GPGPU:${GPU_LICENSE}" 2>&1)

MULTISIM_EXIT=$?
echo "$MULTISIM_OUT" | tail -5

# Extract JobId from multisim output
JOB_ID=$(echo "$MULTISIM_OUT" | grep -oP 'JobId:\s*\K\S+' | head -1)

if [[ -z "$JOB_ID" ]]; then
    warn "Could not detect JobId. Multisim exit code: $MULTISIM_EXIT"
    EXIT_CODE=$MULTISIM_EXIT
else
    log "Job ID: $JOB_ID — waiting for completion..."

    # Block until MD finishes
    JOBCTL="$SCHRODINGER/jobcontrol"
    if [[ -x "$JOBCTL" ]]; then
        # Poll in a loop (jobcontrol -wait may not work on all versions)
        TIMEOUT=$((TOTAL_PS / 10 + 300))  # generous timeout in seconds
        POLL_INTERVAL=10
        ELAPSED_WAIT=0
        while true; do
            STATUS=$("$JOBCTL" -list "$JOB_ID" 2>/dev/null | grep "$JOB_ID" | head -1)
            if echo "$STATUS" | grep -qE "exited|finished|died|killed|cancelled"; then
                EXIT_LINE=$("$JOBCTL" -list "$JOB_ID" 2>/dev/null | grep "$JOB_ID" | head -1)
                log "Job finished: $(echo "$EXIT_LINE" | awk '{print $4, $7}')"
                break
            fi
            if [[ -z "$STATUS" ]]; then
                # Job record may have been cleaned up — it's done
                log "Job completed (record cleaned)"
                break
            fi
            if [[ $ELAPSED_WAIT -ge $TIMEOUT ]]; then
                warn "Timeout after ${TIMEOUT}s — job may still be running"
                break
            fi
            sleep $POLL_INTERVAL
            ELAPSED_WAIT=$((ELAPSED_WAIT + POLL_INTERVAL))
        done
    else
        log "Waiting for output files to appear..."
        # Fallback: wait for .ene file
        for i in $(seq 1 120); do
            if [[ -f "${JOB_NAME}.ene" ]]; then
                sleep 3
                break
            fi
            sleep 5
        done
    fi
    EXIT_CODE=0
fi

END_TIME=$(date +%s)
ELAPSED=$((END_TIME - START_TIME))

echo ""
if [[ $EXIT_CODE -eq 0 ]]; then
    header "MD Completed Successfully"
else
    header "MD Failed (exit code: $EXIT_CODE)"
fi

echo -e "  ${BOLD}Wall time:${NC}     ${ELAPSED}s"
echo -e "  ${BOLD}Output dir:${NC}    $OUTPUT_DIR"

# ── Summary ──
ENERGY_FILE="$OUTPUT_DIR/${JOB_NAME}.ene"
LOG_FILE="$OUTPUT_DIR/${JOB_NAME}.log"

if [[ -f "$ENERGY_FILE" ]]; then
    NROWS=$(tail -n +11 "$ENERGY_FILE" | wc -l)
    echo -e "  ${BOLD}Energy rows:${NC}   $NROWS"
fi

if [[ -f "$LOG_FILE" ]]; then
    TOTAL_RATE=$(grep "Total rate" "$LOG_FILE" | tail -1 | awk '{print $5}')
    echo -e "  ${BOLD}Performance:${NC}   ${TOTAL_RATE:-N/A} ns/day"
fi

# Cleanup tmp
rm -rf "$PROJ_DIR"

echo ""
echo -e "${GREEN}Files:${NC}"
ls -lh "$OUTPUT_DIR"/*.{cms,cpt,cfg,msj,ene,log} 2>/dev/null | awk '{printf "  %-8s %s\n", $5, $NF}'

exit $EXIT_CODE
