#!/usr/bin/env python3
"""
gromacs_meta_gen.py — Generate PLUMED metadynamics input from CLI args
Usage:
  python3 gromacs_meta_gen.py [--dist i j] [--torsion i j k l] [--gyration atoms]
                               [--height 1.0] [--interval 1.0] [--biasfactor 10]
                               [--output plumed.dat]
"""
import sys, argparse

def main():
    parser = argparse.ArgumentParser(description="Generate PLUMED metadynamics input")
    parser.add_argument("--dist", nargs=2, type=int, help="Distance CV atom indices")
    parser.add_argument("--torsion", nargs=4, type=int, help="Torsion CV atom indices")
    parser.add_argument("--gyration", type=str, help="Gyration CV atom selection")
    parser.add_argument("--height", type=float, default=1.0, help="Gaussian height (kJ/mol)")
    parser.add_argument("--interval", type=float, default=1.0, help="Deposition interval (ps)")
    parser.add_argument("--biasfactor", type=float, default=10, help="Well-tempered bias factor")
    parser.add_argument("--temp", type=float, default=300.0, help="Temperature")
    parser.add_argument("--sigma", type=float, default=0.05, help="Gaussian sigma per CV")
    parser.add_argument("--grid-min", type=float, default=-5.0)
    parser.add_argument("--grid-max", type=float, default=5.0)
    parser.add_argument("--grid-bin", type=int, default=200)
    parser.add_argument("-o", "--output", default="plumed.dat")
    args = parser.parse_args()

    cv_defs = []
    cv_names = []
    cv_idx = 0

    if args.dist:
        a1, a2 = args.dist
        cv_defs.append(f"d{cv_idx}: DISTANCE ATOMS={a1},{a2}")
        cv_names.append(f"d{cv_idx}")
        cv_idx += 1
    if args.torsion:
        a1, a2, a3, a4 = args.torsion
        cv_defs.append(f"d{cv_idx}: TORSION ATOMS={a1},{a2},{a3},{a4}")
        cv_names.append(f"d{cv_idx}")
        cv_idx += 1
    if args.gyration:
        cv_defs.append(f"d{cv_idx}: GYRATION TYPE=RADIUS ATOMS={args.gyration}")
        cv_names.append(f"d{cv_idx}")
        cv_idx += 1

    ncv = len(cv_defs)
    if ncv == 0:
        print("ERROR: No CVs specified. Use --dist, --torsion, or --gyration.", file=sys.stderr)
        sys.exit(1)

    arg_str = ",".join(cv_names)
    sigma_str = ",".join([str(args.sigma)] * ncv)
    gmin = ",".join([str(args.grid_min)] * ncv)
    gmax = ",".join([str(args.grid_max)] * ncv)
    gbin = ",".join([str(args.grid_bin)] * ncv)
    pace = int(args.interval * 500)  # 2 fs timestep → 500 steps/ps

    with open(args.output, "w") as f:
        f.write("# PLUMED metadynamics input — auto-generated by gromacs_meta_gen.py\n")
        f.write("# Units: kJ/mol, nm, ps\n")
        f.write(f"# CVs: {ncv}, height: {args.height}, biasfactor: {args.biasfactor}\n\n")
        f.write("# Define collective variables\n")
        for d in cv_defs:
            f.write(d + "\n")
        f.write("\n# Well-tempered metadynamics\n")
        f.write("METAD ...\n")
        f.write(f"   ARG={arg_str}\n")
        f.write(f"   SIGMA={sigma_str}\n")
        f.write(f"   HEIGHT={args.height}\n")
        f.write(f"   PACE={pace}\n")
        f.write(f"   BIASFACTOR={args.biasfactor}\n")
        f.write(f"   TEMP={args.temp}\n")
        f.write(f"   GRID_MIN={gmin}\n")
        f.write(f"   GRID_MAX={gmax}\n")
        f.write(f"   GRID_BIN={gbin}\n")
        f.write(f"   FILE=HILLS\n")
        f.write(f"   LABEL=metad\n")
        f.write("... METAD\n\n")
        f.write("# Print CV values\n")
        f.write(f"PRINT ARG={arg_str} FILE=COLVAR STRIDE=50\n")

    print(f"plumed.dat written: {ncv} CV(s), height={args.height}, biasfactor={args.biasfactor}")

if __name__ == "__main__":
    main()
